# -*- coding: utf-8 -*-
"""Taller_Convolucion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zazqwQhHlxWdfElXFaF3qKLkEjWO8dFb

MARIO ORTIZ


CAMIL0 CALDERIN
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from IPython.display import HTML

"""# Ejercicio 1 — Convolución

En este ejercicio se trabaja con las señales:

- x(t) = u(-t) · e^(3t)  
- h(t) = u(t - 4)  

Se implementa la convolución de forma manual utilizando sumatorias, sin usar funciones predefinidas. Además, se visualiza el proceso mediante una animación donde se observa el desplazamiento de h(t - τ), el producto entre señales y la construcción progresiva de la señal resultante y(t).
"""

# Tiempo
dt = 0.01
t = np.arange(-5, 8, dt)
def u(t):
    return np.where(t >= 0, 1.0, 0.0)
# Señales
x = u(-t) * np.exp(3 * t)

def h(tau):
    return u(tau - 4)
# Convolución manual
y = np.array([np.sum(x * h(ti - t)) * dt for ti in t])
fig, axs = plt.subplots(5, 1, figsize=(10, 16))
fig.suptitle('Convolución — Ejercicio 1', fontsize=13, fontweight='bold')
for ax in axs:
    ax.grid(True, alpha=0.3)
    ax.axhline(0, color='black', lw=0.8)
#  x(t)
axs[0].plot(t, x, color='blue', lw=1.5)
axs[0].set_title('Paso 1 — x(t) = u(−t)·e^(3t)')
axs[0].set_ylabel('x(t)')
axs[0].set_ylim(-0.2, 2.0)
# h(t)
axs[1].plot(t, h(t), color='orange', lw=1.5)
axs[1].set_title('Paso 1 — h(t) = u(t − 4)')
axs[1].set_ylabel('h(t)')
axs[1].set_ylim(-0.2, 1.5)
# h(−τ) invertida
h_inv = h(-t)   # inversión temporal
axs[2].plot(t, h(t),   color='orange', lw=1,   linestyle='--', alpha=0.5, label='h(τ) original')
axs[2].plot(t, h_inv,  color='red',    lw=1.5, label='h(−τ) invertida')
axs[2].set_title('Paso 2 — Inversión: h(−τ)')
axs[2].set_ylabel('h(−τ)')
axs[2].set_ylim(-0.2, 1.5)
axs[2].legend(fontsize=8)
# animación — h(t−τ) desplazada y producto
axs[3].plot(t, x, color='blue', alpha=0.3, label='x(τ)')
line_h,  = axs[3].plot([], [], color='red',  lw=1.5, label='h(t−τ)')
fill     = [axs[3].fill_between(t, 0, 0, color='purple', alpha=0.3)]
axs[3].set_title('Pasos 3 y 4 — h(t−τ) desplazada · x(τ) = producto')
axs[3].set_ylabel('Amplitud')
axs[3].set_ylim(-0.2, 2.0)
axs[3].legend(fontsize=8, loc='upper right')
# y(t) resultante
axs[4].plot(t, y, '--', color='gray', alpha=0.5, lw=1)
line_y,   = axs[4].plot([], [], color='green', lw=2)
point_y,  = axs[4].plot([], [], 'o', color='green', ms=6)
axs[4].set_title('Pasos 5 y 6 — y(t) = integral acumulada')
axs[4].set_ylabel('y(t)')
plt.tight_layout()
#análisis al finalizar animación
y_max   = np.max(y)
t_max   = t[np.argmax(y)]
t_start = t[np.where(y > 1e-6)[0][0]]  if np.any(y > 1e-6)  else None
t_end   = t[np.where(y > 1e-6)[0][-1]] if np.any(y > 1e-6)  else None
# ── Animación
idx = np.arange(0, len(t), 8)
def animar(i):
    k = idx[i]
    ti = t[k]
    h_shift = h(ti - t)
    line_h.set_data(t, h_shift)
    fill[0].remove()
    fill[0] = axs[3].fill_between(t, 0, x * h_shift, color='purple', alpha=0.3)
    mask = t <= ti
    line_y.set_data(t[mask], y[mask])
    point_y.set_data([ti], [y[k]])
# analisis final
    axs[4].set_xlabel(f'τ actual = {ti:.2f}   |   y(t) actual = {y[k]:.4f}', fontsize=9)
    return line_h, line_y, point_y, fill[0]
print("=" * 45)
print("PASO 7 — Análisis del resultado")
print("=" * 45)
print(f"  Valor máximo de y(t) : {y_max:.4f}")
print(f"  Ocurre en t          : {t_max:.2f}")
if t_start and t_end:
    print(f"  Soporte aproximado   : [{t_start:.2f}, {t_end:.2f}]")
print(f"  Forma                : escalón desplazado con decaimiento")
print("=" * 45)
ani = animation.FuncAnimation(fig, animar, frames=len(idx), interval=40, blit=False)
HTML(ani.to_jshtml())

"""#Ejercicio 2 — Convolución

En este caso se utilizan dos señales iguales:

- x(t) = h(t) = u(t + 0.5) − u(t − 0.5)  

Estas señales corresponden a un pulso rectangular centrado en el origen. La convolución se calcula manualmente y se representa gráficamente junto con una animación que muestra el proceso de solapamiento entre ambas señales.

El resultado esperado es una señal triangular, lo cual confirma que la implementación es correcta.
"""

# Tiempo
dt = 0.01
t = np.arange(-2, 3, dt)
# Pulso rectangular
x = np.where((t >= -0.5) & (t <= 0.5), 1.0, 0.0)
def h(tau):
    return np.where((tau >= -0.5) & (tau <= 0.5), 1.0, 0.0)
# Convolución manual
y = np.array([np.sum(x * h(ti - t)) * dt for ti in t])
fig, axs = plt.subplots(5, 1, figsize=(10, 16))
fig.suptitle('Convolución — Ejercicio 2', fontsize=13, fontweight='bold')
for ax in axs:
    ax.grid(True, alpha=0.3)
    ax.axhline(0, color='black', lw=0.8)
#  x(τ)
axs[0].plot(t, x, color='blue', lw=1.5)
axs[0].set_title('Paso 1 — x(τ): pulso rectangular')
axs[0].set_ylim(-0.2, 1.5)
# h(τ) original
axs[1].plot(t, h(t), color='orange', lw=1.5)
axs[1].set_title('Paso 1 — h(τ): pulso rectangular')
axs[1].set_ylim(-0.2, 1.5)
# h(−τ) invertida
h_inv = h(-t)
axs[2].plot(t, h(t),  color='orange', lw=1, linestyle='--',
            alpha=0.5, label='h(τ) original')
axs[2].plot(t, h_inv, color='red', lw=1.5, label='h(−τ) invertida')
axs[2].set_title('Paso 2 — Inversión: h(−τ)')
axs[2].set_ylim(-0.2, 1.5)
axs[2].legend(fontsize=8)
#  animación
axs[3].plot(t, x, color='blue', alpha=0.3, label='x(τ)')
line_h, = axs[3].plot([], [], color='red', lw=1.5, label='h(t−τ)')
fill    = [axs[3].fill_between(t, 0, 0, color='purple', alpha=0.3)]
axs[3].set_title('Pasos 3 y 4 — h(t−τ) desplazada · x(τ)')
axs[3].set_ylim(-0.2, 1.5)
axs[3].legend(fontsize=8, loc='upper right')
# y(t)
axs[4].plot(t, y, '--', color='gray', alpha=0.5)
line_y,  = axs[4].plot([], [], color='green', lw=2)
point_y, = axs[4].plot([], [], 'o', color='green', ms=6)
axs[4].set_title('Pasos 5 y 6 — y(t) = integral acumulada')
axs[4].set_ylim(-0.2, 1.5)
plt.tight_layout()
#Animación
idx = np.arange(0, len(t), 4)
def animar(i):
    k = idx[i]
    ti = t[k]
    h_shift = h(ti - t)
    line_h.set_data(t, h_shift)
    fill[0].remove()
    fill[0] = axs[3].fill_between(t, 0, x * h_shift, color='purple', alpha=0.3)
    mask = t <= ti
    line_y.set_data(t[mask], y[mask])
    point_y.set_data([ti], [y[k]])
    # etiqueta dinámica
    axs[4].set_xlabel(
        f't = {ti:.2f}   |   y(t) = {y[k]:.4f}', fontsize=9
    )
    return line_h, line_y, point_y, fill[0]
ani = animation.FuncAnimation(
    fig, animar, frames=len(idx), interval=40, blit=False
)
# análisis final
y_max  = np.max(y)
t_max  = t[np.argmax(y)]
soport = t[y > 1e-6]
t_ini  = soport[0]  if len(soport) else None
t_fin  = soport[-1] if len(soport) else None
print("=" * 45)
print("PASO 7 — Análisis del resultado")
print("=" * 45)
print(f"  Señales              : dos pulsos rect. de ancho 1")
print(f"  Valor máximo de y(t) : {y_max:.4f}")
print(f"  Ocurre en t          : {t_max:.2f}")
if t_ini is not None:
    print(f"  Soporte aproximado   : [{t_ini:.2f}, {t_fin:.2f}]")
    print(f"  Ancho del soporte    : {t_fin - t_ini:.2f}  (suma de anchos: 1+1=2)")
print(f"  Forma                : triángulo (convolución de dos rect.)")
print("=" * 45)

HTML(ani.to_jshtml())

# En una celda de Colab
import os
# Guarda localmente primero y revisa el tamaño
